### ISSUE TITLE
Add `return` event

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Godot-EventSystem#31]
### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This event is a similar implementation of `return` keyword. Whetever is called, ends the timeline execution.

**Comment by Crystalwarrior** [comment]
Do not call it "return", call it "end timeline". Calling it return would actually be extremely confusing otherwise especially if paired with the "Condition" event, so someone could put in a "return" event, expecting it to return back to where the condition was called from, only for it to suddenly end execution.
I still want an equivalent of a Return event though, but call it "Return to Previous Timeline", or simply "Go Back".
